spring.application.name=MIS

# ???????
server.port=8080

# ???????
spring.datasource.url=jdbc:mysql://localhost:3306/scut_mis?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=LExuwenle060912@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# MyBatis ??
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis.type-aliases-package=com.scut.mis.entity

# ????????????????Java???
mybatis.configuration.map-underscore-to-camel-case=true
